### ISSUE TITLE
caching fails when the number of minted blocks is large

### ISSUE THREAD

**Issue by dmakarov** [gpoore/minted#78] opened 2015-06-10 11:17 UTC
I have about 470 minted blocks in a LaTeX file.  After processing approximately 200 blocks the following error happens

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 62, in <module>
    import os
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 398, in <module>
    import UserDict
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 83, in <module>
    import _abcoll
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 11, in <module>
    from abc import ABCMeta, abstractmethod
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 8, in <module>
    from _weakrefset import WeakSet
ImportError: No module named _weakrefset

./book.tex:7435: Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7435 \end{minted}
```

When I disable caching ```[cache=false]``` the file compiles to pdf without a problem.

The version of minted:
```
package:     minted
category:    Package
shortdesc:   Highlighted source code for LaTeX.
longdesc:    The package that facilitates expressive syntax highlighting in LaTeX using the powerful Pygments library. The package also provides options to customize the highlighted source code output using fancyvrb.
installed:   Yes
revision:    36197
sizes:       src: 173k, doc: 613k, run: 61k
relocatable: No
cat-version: 2.0
cat-date:    2015-02-02 13:51:15 +0100
cat-license: lppl1.3
collection:  collection-latexextra
```

**Comment by gpoore** [comment] 2015-06-10 12:13
Based on the Python error message, this looks like a general Python issue, rather than something `minted`-specific. (Also, just in terms of shear numbers, I think some `minted` users have thousands of code blocks without any problems, so that shouldn't be a factor.)

If you are using `virtualenv`, then you may be [affected by a bug](https://github.com/pypa/virtualenv/issues/76). Otherwise, there is likely something else wrong with your Python installation.

**Comment by dmakarov** [comment] 2015-06-10 12:15
Why doesn't pygmentize (python) fail to process the blocks when caching is disabled?

**Comment by gpoore** [comment] 2015-06-10 12:45
I haven't read a lot about `_weakrefset` import errors, but what I have found indicates they are often associated with `virtualenv` or similar special configurations. Also, apparently some `_weakrefset` errors are NOT consistent and are somehow related to garbage collection, so that in some cases code will only fail less than 1% of the time. My guess is that the non-caching pygmentize runs are not (or have not yet) triggered the issue due to this inconsistent behavior.

Have you tracked down your `_weakrefset.py` to make sure it actually exists? If it does, that suggests a configuration issue.

**Comment by dmakarov** [comment] 2015-06-10 12:55
Yes, it does exist, and its imported fine, when pigmentize runs not from minted. Also, as I say the first two hundred or so minted blocks are processed fine, no errors.  After certain number of minted blocks python starts breaking with other import errors, `_weakrefset` is usually the first one.  If python were configured/installed incorrectly, the first minted block would most likely trigger the problem. But this only happens after about 200 hundred minted blocks were processed, then say two hundred first suddenly triggers the python installation problem?  Do you believe it's the case?

I'm running luatex processor.  I don't know how it runs the subprocesses, e.g. how it starts `pygmentize` script for minted blocks. Obviously there's some difference in how `pygmentize` is executed when minted caching is enabled and when it's disabled.  Either the input to the pygmentize script is different in these two cases, or the script is executed in a different environment. What exactly is happening I don't know.  But it's not the installation of python on my system.  If it were the installation, it wouldn't work when minted caching is disabled, but it does work perfectly in the latter case.

**Comment by gpoore** [comment] 2015-06-10 13:39
If there are ever any other errors before `_weakrefset`, it would help to see those.

luatex runs `pygmentize` the same way with and without caching. The only difference is that with caching, `pygmentize` is given a different location for saving the output. But in both cases, luatex calls `pygmentize` using the same environment and using the same input.

I just ran 1000 blocks with luatex with no errors under Windows with Python 3.4. I know of [at least one case of 3000+ working fine](https://github.com/gpoore/minted/issues/61#issuecomment-67926389).

Can you give me your operating system, Python version (including micro version number; all versions if multiple installed), and PYTHONPATH and PYTHONHOME (if any)?

**Comment by dmakarov** [comment] 2015-06-10 13:50
OSX 10.10.3
Python 2.7.6 (only one installed, no settings of PYTHONPATH or PYTHONHOME)

The first failure is for `_weakrefset`, then luatex keeps running, and the next minted block fails
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 62, in <module>
    import os
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 49, in <module>
    import posixpath as path
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 17, in <module>
    import warnings
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/warnings.py", line 6, in <module>
    import linecache
ImportError: No module named linecache

./book.tex:7158: Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7158 \end{minted}
```

then another one:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 62, in <module>
    import os
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 49, in <module>
    import posixpath as path
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 15, in <module>
    import stat
ImportError: No module named stat

./book.tex:7165: Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7165 \end{minted}
```

keeps running, then finally

```
dyld: Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
  Referenced from: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python: open() failed with errno=24
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python: open() failed with errno=24

./book.tex:7205: Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7205 \end{minted}
                 
./book.tex:7218: I can't write on file `book.pyg'.
<to be read again> 
\relax 
l.7218 \begin{minted}[linenos]{c++}
                                 
Please type another output file name
./book.tex:7218: Emergency stop.
```

**Comment by dmakarov** [comment] 2015-06-10 13:55
Also I should mention if I keep rerunning luatex, all the minted blocks are eventually cached, until luatex fails with `too many open files` error. It is as if it keeps open all the cached minted files. So even if not for the python failures, cache doesn't work (with luatex at least) where there are minted blocks, but that's not minted's problem I guess.

```
This is LuaTeX, Version beta-0.79.1 (TeX Live 2014) (rev 4971)
```

**Comment by gpoore** [comment] 2015-06-10 14:01
I think that when `pygmentize` crashes, either it leaves a file open, or it interferes with luatex's file handling.

It looks like the problem is occurring with an `\inputminted`. Are you inputting a file called `site.py` anywhere in the document?

**Comment by dmakarov** [comment] 2015-06-10 14:06
No, I'm not inputting any file (including site.py) anywhere in `book.tex`. And `book.tex` is a single tex file being processed, no other includes or anything external. No explicit command `\inputminted` anywhere in `book.tex`, only the 470 blocks `\begin{minted}[linenos]{c++}` ... `\end{minted}`.

**Comment by dmakarov** [comment] 2015-06-10 14:16
If you believe that when caching is enabled the input to `pygmentize` is the same as when caching is disabled, I'm ok to close this issue report.  The problem is probably then in luatex processor and its resource or subprocess management.  It would be interesting to trace how `pygmentize` is invoked in each case and on what input...

**Comment by gpoore** [comment] 2015-06-10 14:19
I've done some additional research on `_weakrefset`, and haven't made any progress. It seems that these bugs are related to `virtualenv` or `site.py` (not the case here), or are just mysterious. It seems that these bugs are often hard to reproduce.

Since luatex and `minted` work on other systems, I think this must be system-specific. I doubt that luatex is the issue, though I suppose it's possible...I would try reinstalling or upgrading Python.

**Comment by dmakarov** [comment] 2015-06-10 14:23
It's not python. I think since with caching enabled all those hundred files are open simultaneously, some limit is reached and the OSX prevents python (as luatex's child process) from opening any new files, it happens to be `_weakrefset.py`.

**Comment by gpoore** [comment] 2015-06-10 14:30
Normally, `pygmentize` and luatex close files as they go along, so no more than one temp file of code is ever open at a given time. I think the only reason for the file limit error is that the `_weakrefset` error is preventing some files from being closed properly.

**Comment by dmakarov** [comment] 2015-06-10 14:33
So I just bumped the limit `ulimit -n 4096` and everything works with caching enabled.  Indeed it's the number of open files, that breaks things.

**Comment by dmakarov** [comment] 2015-06-10 14:35
No, I think you're wrong, when caching is enabled, all the files from _minted- subidr are open all the time while luatex is running. _weakrefset happens because python cannot load it because there's no file handles available. If you look at other errors I pasted in previous comments, eventually even dyld can't open a new file. The error 24 means no more file handles.

**Comment by dmakarov** [comment] 2015-06-10 14:37
Anyway, this issue can be closed.  If someone faces the same problem, the solution is to increase the limit on the number of open files: `$ ulimit -n 4096` (or smaller number)

**Comment by gpoore** [comment] 2015-06-10 14:48
Thanks for tracking that down. Different systems must handle this very differently, because when I run 1000 blocks, the files are closed as soon as they are generated.

I will leave this open for now, and add a note to the next release about `ulimit` being needed under some conditions.

**Closed** 2015-06-23 13:41 UTC
