### ISSUE TITLE
"missing pygments output"

### ISSUE THREAD

**Issue by zackp30** [gpoore/minted#81] opened 2015-07-22 09:51 UTC
This (at least for me):
```latex
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}{python}
  1 + 2
\end{minted}
\end{document}
```
Produces
```
! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.3 \begin
          {document}^^M
? 
/usr/bin/pygmentize
(./thing.aux) (/home/zack/.tex/texmf-dist/tex/latex/xcolor/xcolor.sty
(/home/zack/.tex/texmf-dist/tex/latex/latexconfig/color.cfg)
(/home/zack/.tex/texmf-dist/tex/xelatex/xetex-def/xetex.def))

! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.3 \begin{document}
                    ^^M
? 
(./thing.mintedmd5)
(./_minted-thing/7a7f79592735278d565584f682663d7540301d44.pygtex) [1]
(./thing.aux) )
Output written on thing.pdf (1 page).
Transcript written on thing.log.
```

I've found a bug about this, but increasing `ulimit -n` didn't help.

Is there a way to see the exact command that is used to invoke `pygmentize`?

Thanks!

**Comment by gpoore** [comment] 2015-07-24 16:55
If you look in `minted.sty` around line 1000 (depending on version), there is a commented-out line just after `% For debugging, uncomment:`.  If you uncomment that line, the `pygmentize` command will be written to the log.

I should probably add a package option `debug` to make this sort of thing simpler.

**Comment by zackp30** [comment] 2015-07-24 17:39
No extra output is produced. :frowning:

**Comment by zackp30** [comment] 2015-07-24 17:40
This is using `xelatex` if that helps.

**Comment by zackp30** [comment] 2015-07-24 17:43
I also tried invoking `pygmentize` manually and it works fine.

**Comment by gpoore** [comment] 2015-07-25 06:22
You want to replace `% \immediate\typeout{\minted@cmd}%` with `\immediate\typeout{\minted@cmd}%`. That should add the Pygments command to the `xelatex` output.

Are you using any build tools? Because those often have compatibility issues with packages like `minted`.

**Comment by zackp30** [comment] 2015-07-25 08:12
@gpoore I uncommented that line, yes, no effect.

I'm not using any build tools, just the good ol' command line.

**Comment by gpoore** [comment] 2015-07-25 16:47
There should be no effect in the document, but you should see a line in the command-line output. If you aren't seeing that, then something is really strange, and I'm not sure what is going on.

**Comment by jstac** [comment] 2015-07-27 14:18
Similar problem for me after updating to minted 2.0:

! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.76 \usemintedstyle
                    {friendly}^^M
? 

This is after trying to compile with `pdflatex -shell-escape et.tex`

I'm using texlive and Python via the Anaconda distribution.  `pygments` imports fine.

**Comment by jstac** [comment] 2015-07-27 14:20
Related:

http://tex.stackexchange.com/questions/256181/package-minted-error-missing-pygments-output-latex

**Comment by gpoore** [comment] 2015-07-27 17:19
I use Anaconda Python with TeX Live and MiKTeX, and haven't been able to figure out a way to reproduce the error.

The following would help.
* Operating system and version
* TeX distribution, including version
* Python version
* A **complete** copy of the log

**Comment by jstac** [comment] 2015-07-27 17:42
Thanks a lot for getting back to me and also for providing a great service to the community.  Here's what I have:

```
Description:	Ubuntu 15.04
Release:	15.04

john@godzilla-nyu:~/temp$ pdflatex -v
pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian)
kpathsea version 6.2.1dev

Compiled with libpng 1.6.13; using libpng 1.6.13
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.30.0

john@godzilla-nyu:~/temp$ tex -v
TeX 3.14159265 (TeX Live 2015/dev/Debian)
kpathsea version 6.2.1dev

john@godzilla-nyu:~/temp$ python
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
```

Here's a minimal version that generates the error:

```
\documentclass{article}
\usepackage{minted}
\usemintedstyle{friendly}
\newminted{python}{mathescape, baselinestretch=1, framesep=2mm}
\begin{document}
testing
\end{document}
```

Here's the complete log

```
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=pdflatex 2015.7.2)  27 JUL 2015 13:34
entering extended mode
 \write18 enabled.
 %&-line parsing enabled.
**et_minted_test.tex
(./et_minted_test.tex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2014/09/29 v1.4h Standard LaTeX file (size option)
)
\c@part=\count79
\c@section=\count80
\c@subsection=\count81
\c@subsubsection=\count82
\c@paragraph=\count83
\c@subparagraph=\count84
\c@figure=\count85
\c@table=\count86
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(/usr/share/texlive/texmf-dist/tex/latex/minted/minted.sty
Package: minted 2015/07/09 v2.1dev Yet another Pygments shim for LaTeX

(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2014/05/08 v1.15 key=value parser (DPC)
\KV@toks@=\toks14
)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
Package: kvoptions 2011/06/30 v3.11 Key value format for package options (HO)

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty
Package: ltxcmds 2011/11/09 v1.22 LaTeX kernel commands for general use (HO)
)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
Package: kvsetkeys 2012/04/25 v1.16 Key value parser (HO)

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty
Package: infwarerr 2010/04/08 v1.3 Providing info/warning/error messages (HO)
)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
Package: etexcmds 2011/02/16 v1.5 Avoid name clashes with e-TeX commands (HO)

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty
Package: ifluatex 2010/03/01 v1.3 Provides the ifluatex switch (HO)
Package ifluatex Info: LuaTeX not detected.
)
Package etexcmds Info: Could not find \expanded.
(etexcmds)             That can mean that you are not using pdfTeX 1.50 or
(etexcmds)             that some package has redefined \expanded.
(etexcmds)             In the latter case, load this package earlier.
)))
(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Package: fancyvrb 2008/02/07

Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz)
\FV@CodeLineNo=\count87
\FV@InFile=\read1
\FV@TabBox=\box26
\c@FancyVerbLine=\count88
\FV@StepNumber=\count89
\FV@OutFile=\write3
) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty
Package: float 2001/11/08 v1.3d Float enhancements (AL)
\c@float@type=\count90
\float@exts=\toks15
\float@box=\box27
\@float@everytoks=\toks16
\@floatcapt=\box28
)
(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty
Package: ifthen 2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
)
(/usr/share/texlive/texmf-dist/tex/latex/tools/calc.sty
Package: calc 2014/10/28 v4.3 Infix arithmetic (KKT,FJ)
\calc@Acount=\count91
\calc@Bcount=\count92
\calc@Adimen=\dimen103
\calc@Bdimen=\dimen104
\calc@Askip=\skip43
\calc@Bskip=\skip44
LaTeX Info: Redefining \setlength on input line 75.
LaTeX Info: Redefining \addtolength on input line 76.
\calc@Ccount=\count93
\calc@Cskip=\skip45
)
(/usr/share/texlive/texmf-dist/tex/latex/ifplatform/ifplatform.sty
Package: ifplatform 2010/10/22 v0.4 Testing for the operating system

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty
Package: pdftexcmds 2011/11/29 v0.20 Utility functions of pdfTeX for LuaTeX (HO
)

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty
Package: ifpdf 2011/01/30 v2.3 Provides the ifpdf switch (HO)
Package ifpdf Info: pdfTeX in PDF mode is detected.
)
Package pdftexcmds Info: LuaTeX not detected.
Package pdftexcmds Info: \pdf@primitive is available.
Package pdftexcmds Info: \pdf@ifprimitive is available.
Package pdftexcmds Info: \pdfdraftmode found.
)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/catchfile.sty
Package: catchfile 2011/03/01 v1.6 Catch the contents of a file (HO)
)
runsystem(uname -s > "et_minted_test.w18")...executed.


(./et_minted_test.w18)
runsystem(rm -- "et_minted_test.w18")...executed.

)
(/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty
Package: etoolbox 2011/01/03 v2.1 e-TeX tools for LaTeX

(/usr/share/texlive/texmf-dist/tex/latex/etex-pkg/etex.sty
Package: etex 1998/03/26 v2.0 eTeX basic definition package (PEB)
\et@xins=\count94
)
\etb@tempcnta=\count95
)
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.tex
\@xs@message=\write4
\integerpart=\count96
\decimalpart=\count97
)
Package: xstring 2013/10/13  v1.7c  String manipulations (C Tellechea)
)
(/usr/share/texlive/texmf-dist/tex/latex/lineno/lineno.sty
Package: lineno 2005/11/02 line numbers on paragraphs v4.41
\linenopenalty=\count98
\output=\toks17
\linenoprevgraf=\count99
\linenumbersep=\dimen105
\linenumberwidth=\dimen106
\c@linenumber=\count100
\c@pagewiselinenumber=\count101
\c@LN@truepage=\count102
\c@internallinenumber=\count103
\c@internallinenumbers=\count104
\quotelinenumbersep=\dimen107
\bframerule=\dimen108
\bframesep=\dimen109
\bframebox=\box29
LaTeX Info: Redefining \\ on input line 3056.
)
\minted@appexistsfile=\read2
\FV@BreakIndent=\dimen110
\FV@BreakSymbolSepLeft=\dimen111
\FV@BreakSymbolSepRight=\dimen112
\FV@BreakSymbolIndentLeft=\dimen113
\FV@BreakSymbolIndentRight=\dimen114
\c@FancyVerbLineBreakLast=\count105
\FV@LineBox=\box30
\FV@LineIndentBox=\box31
\minted@bgbox=\box32
\minted@code=\write5
\c@minted@FancyVerbLineTemp=\count106
\@float@every@listing=\toks18
\c@listing=\count107
)
runsystem(mkdir -p "_minted-et_minted_test")...executed.

runsystem(pygmentize -S default -f latex -P commandprefix=PYGdefault > "_minted
-et_minted_test/ default.pygstyle")...executed.



! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5 \usemintedstyle
                   {friendly}^^M
? x
 
Here is how much of TeX's memory you used:
 2932 strings out of 493105
 53578 string characters out of 6137073
 141296 words of memory out of 5000000
 6405 multiletter control sequences out of 15000+600000
 3808 words of font info for 15 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 37i,1n,21p,829b,60s stack positions out of 5000i,500n,10000p,200000b,80000s
No pages of output.
PDF statistics:
 0 PDF objects out of 1000 (max. 8388607)
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
```

**Comment by gpoore** [comment] 2015-07-28 17:27
@jstac Here are a few things to try.

* It looks like you're using the 2.1 development version. Try [version 2.0](https://github.com/gpoore/minted/releases). It's possible there is a system-dependent bug in the development version.
* Try `\usepackage[cache=false]{minted}`. If that works, it would narrow down the possible source of issues.

If neither of those helps, I suppose it's also possible that something has changed in TeX Live 2015 that is causing an incompatibility somewhere. I won't have a chance to look into that possibility for at least a few days.

**Comment by alessandrobattisti** [comment] 2015-07-31 11:57
I had the same problems.
Now using ```\usepackage[cache=false]{minted}```, with 2.1 development version, works fine.
Thank you

**Comment by jstac** [comment] 2015-07-31 13:58
Worked for me too!  Thanks!

**Comment by philipobrien** [comment] 2015-07-31 14:03
How do you specify you want the 2.1 development version?

**Comment by alessandrobattisti** [comment] 2015-07-31 14:27
I added this [minted.sty](https://github.com/gpoore/minted/blob/master/source/minted.sty) to my project.

**Comment by philipobrien** [comment] 2015-07-31 14:35
@alessandrobattisti Thanks for the pointer. Unfortunately it didn't fix things for me

**Comment by alessandrobattisti** [comment] 2015-07-31 15:24
If you want try with this simple [example](http://www.filedropper.com/problems-minted-latex), compile with ```pdflatex -shell-escape main.tex```

**Comment by philipobrien** [comment] 2015-07-31 15:31
@alessandrobattisti Thanks, that worked perfectly! I use Texpad, and compiling there produces a pdf with no minted output. Strange.

**Comment by philipobrien** [comment] 2015-07-31 15:37
Just sorted it on Texpad now thanks to [this answer on SO](http://tex.stackexchange.com/questions/63160/minted-working-from-terminal-but-not-texpad). 

```
\usepackage[cache=false]{minted}
```

becomes

```
\usepackage[cache=false,outputdir=.texpadtmp]{minted}
```

**Comment by jstac** [comment] 2015-08-04 10:33
I take it the disadvantage of `cache=false` is that it slows down compilation...

**Comment by gpoore** [comment] 2015-08-05 01:48
@jstac Yes, `cache=false` recreates all highlighting at each compile, which is **much** slower.

I'm just getting back to having consistent computer and internet access after two weeks traveling. I've determined that there isn't anything new in TeX Live 2015 that is intrinsically causing issues. I have some ideas about what is happening, but may have to dig a bit more.

**Comment by gpoore** [comment] 2015-08-05 11:52
I found a bug in the 2.1dev version that could cause caching to fail on non-Windows systems. This is fixed in b75fea3. Please let me know if any issues continue (with default `\usepackage{minted}`, no `cache=false`).

**Comment by jstac** [comment] 2015-08-05 12:54
Worked for me, many thanks!

**Comment by alessandrobattisti** [comment] 2015-08-06 09:18
Worked for me too (Ubuntu 15.04). Thanks!

**Comment by gpoore** [comment] 2015-08-06 14:20
I'm closing this since it seems resolved. If anyone encounters the same error with the latest commit, please re-open.

**Closed by gpoore** 2015-08-06 14:20 UTC
Labels: bug

**Comment by zackp30** [comment] 2015-08-07 09:05
Thanks! Seems fixed for me.

However, I am experiencing another issue, which I shall open another issue for, but it seems to be related to this.

**Comment by raphaklr** [comment] 2015-08-25 09:28
@philipobrien Thanks for the hint, you saved my day!

**Comment by philipobrien** [comment] 2015-08-25 09:36
@raphaklr :+1:

**Comment by ljani** [comment] 2017-02-05 19:20
Adding `cache=false` seemed to fix my problems as well:
```tex
\RequirePackage[outputdir=out,cache=false]{minted}
```
Otherwise the `main.out.pyg` file would not be created.

I'm running TeX Live 2016 compiled from CTAN with Mint `v2.4.1` on [`debian:jessie`](https://hub.docker.com/_/debian/) Docker image via Docker Machine where the TeX sources are mounted from my Windows box. I'm not sure how the caching is build, but I guess the mount might cause some problems?

**Comment by guicho271828** [comment] 2017-09-26 06:24
related: this seems incompatible to `import` package that allows relative input/include.

**Comment by gpoore** [comment] 2017-09-26 11:45
@guicho271828 The `import` package is actually a separate situation, since it modifies `\input`. See #172 for details.

**Comment by guicho271828** [comment] 2017-09-26 14:10
@gpoore oh yes, thanks!

**Comment by awa5114** [comment] 2022-04-22 12:19
@gpoore I've noticed that if the compiled TeX file is in my working directory, everything compiles fine. However, if I'm compiling from a parent directory, the error occurs. Here's an example of the `latexmk` command I'm running to compile from outside the directory:

```
latexmk --shell-escape -lualatex -jobname=test -outdir=notes/ .\notes\minted.tex
```

**Comment by gpoore** [comment] 2022-04-22 13:02
@awa5114 You generally want to compile from the document directory. If you compile in another directory, there is no way for `minted` to determine where your document is located (LaTeX has this information, but I don't believe it is made available to packages). Using another directory can also cause issues for some other packages. If you need files from another directory, perhaps look into environment variables (`TEXINPUTS`). This particular issue is nearly 7 years old and was primarily due to bugs in caching when caching was first introduced.
