### ISSUE TITLE
write18 not enabled in new luatex

### ISSUE THREAD

**Issue by davidcarlisle** [gpoore/minted#112] opened 2016-03-15 23:01 UTC
luatex from 0.87 (and so 0.90 planned for texlive 2016) does not enable \write18 (as it has 256 available write streams so 18 is now in the "normal" range).

Since the January 2016 latex release the tools directory has included a shellesc package that addresses this in two ways

1, in new luatex it overloads \write to check for 18 and if given that number uses \directlua to access os.exec to call the system  This allows minted still to work see the minted-test.tex at

https://github.com/josephwright/luatex85

2 it defines a \ShellEscape command that can be used on any engine to give a slightly more
understandable syntax to the operating system, this of course uses \write18 or lua os.exec depending on the tex engine in use.

so you could always load shellesc and use \ShellEscape or just load it on new luatex (eg if \pdffeedback is defined) and use \write18 or could not load shellesc but use a similar switch to use os.exec in luatex.

Sorry to be the bearer of bad news but the new luatex will break _lots_ of packages. Fortunately in this case the update required is quite localised.

**Comment by gpoore** [comment] 2016-03-16 02:40
Thanks for the information. I need to redo all of the `\write18` anyway to deal with an existing issue (#85), so I'll probably just switch everything over to `shellesc`.

**Comment by adl** [comment] 2016-05-18 15:04
LuaLaTeX 0.95.0 landed in Debian unstable recently, and my documents using minted (and other packages relying on `\write18`) broke.

For reference, adding
```
\RequirePackage{shellesc}
```
as the first line of the document provide a temporary fix until packages are updated to not rely on `\write18`.

**Comment by gpoore** [comment] 2016-05-18 15:35
@adl The next version of `minted`, with a fix for this, should be on CTAN by the end of next week.

**Comment by gpoore** [comment] 2016-06-01 04:01
Everything is switched over to use `\ShellEscape` from `shellesc` now. If `shellesc` isn't present, then `\ShellEscape` is defined.

There was a bug in `shellesc` v0.01b that overwrote `\ShellEscape` with the definition of `\DelayedShellEscape`. I added a check and patch for this, so that TeX Live 2015 users won't have trouble if they download the latest `minted.sty`. `shellesc` 0.01c is on CTAN, so TeX Live 2016 should be fine.

The package-loading process in case it's useful elsewhere:
```latex
\IfFileExists{shellesc.sty}
 {\RequirePackage{shellesc}
  \@ifpackagelater{shellesc}{2016/04/29}
   {}
   {\protected\def\ShellEscape{\immediate\write18 }}}
 {\protected\def\ShellEscape{\immediate\write18 }}
```
I've tested with `lualatex` (0.80), `pdflatex`, and `xelatex`, with both `shellesc` 0.01b and 0.01c, and everything seems fine.

**Comment by ArTourter** [comment] 2016-06-13 14:18
Hi,

It looks like the \IfFileExists test is done too late in the code. it needs to be done before loading ifplatform as the shellescape or write18 is tested by a package loaded by ifplatform.

**Comment by gpoore** [comment] 2016-06-13 15:57
@ArTourter Thanks for pointing that out.

Did you actually get an error, or just find the inconsistency? `minted` is only using `\ifwindows` from `ifplatform`, which should essentially never actually use `\write18`. So I'd be interested if you found a case where `\ifwindows` actually had to resort to `\write18`.

**Comment by ArTourter** [comment] 2016-06-13 17:32
No, I actually got an error.
I attach the simple mwe and the log that goes with it.
Basically it needs to be loaded before pdftexcmds but ifplatforms loads it anyway hence why it needs to be loaded before ifplatforms (and you should be able to remove the line loading pdftexcmds  unless older versions of ifplatforms do not load it.

[test3.zip](https://github.com/gpoore/minted/files/312374/test3.zip)

**Comment by ArTourter** [comment] 2016-06-13 18:39
The following patch works for me (commented the line loading pdftexcmds rather that deleted it)

```
--- /usr/local/texlive/2016/texmf-dist/tex/latex/minted/minted.sty	2016-06-09 23:52:48.000000000 +0100
+++ minted.sty	2016-06-13 18:24:24.000000000 +0100
@@ -34,12 +34,6 @@
 \RequirePackage{float}
 \RequirePackage{ifthen}
 \RequirePackage{calc}
-\RequirePackage{ifplatform}
-\RequirePackage{pdftexcmds}
-\RequirePackage{etoolbox}
-\RequirePackage{xstring}
-\RequirePackage{lineno}
-\RequirePackage{framed}
 \IfFileExists{shellesc.sty}
  {\RequirePackage{shellesc}
   \@ifpackagelater{shellesc}{2016/04/29}
@@ -50,6 +44,12 @@
   \@ifpackageloaded{color}{}{%
     \@ifpackageloaded{xcolor}{}{\RequirePackage{xcolor}}}%
 }
+\RequirePackage{ifplatform}
+%\RequirePackage{pdftexcmds}
+\RequirePackage{etoolbox}
+\RequirePackage{xstring}
+\RequirePackage{lineno}
+\RequirePackage{framed}
 \DeclareVoidOption{chapter}{\def\minted@float@within{chapter}}
 \DeclareVoidOption{section}{\def\minted@float@within{section}}
 \DeclareBoolOption{newfloat}
```

**Comment by gpoore** [comment] 2016-06-13 19:42
@ArTourter It should be fixed now.

I had misunderstood the `ifplatform` documentation. `\ifwindows` usually doesn't need `\write18`, but `ifplatform` will use `\write18` when it is loaded if shell escape is enabled, regardless of which commands are ultimately used.

**Comment by ArTourter** [comment] 2016-06-14 07:10
I can confirm that the last commit works for me.
Thanks

**Closed** 2016-06-15 18:32 UTC
Labels: enhancement
