### ISSUE TITLE
escapeinside option doesn't work inside of beamer

### ISSUE THREAD

**Issue by heathermiller** [gpoore/minted#70] opened 2015-04-01 11:41 UTC
From the documentation... If I simply insert:

    \begin{minted}[escapeinside=||]{py}
    def f(x):
    y = x|\colorbox{green}{**}|2
    return y
    \end{minted}

Into a beamer slide, nothing happens. The characters that are supposed to be escaped aren't escaped.

![screen shot 2015-04-01 at 1 40 26 pm](https://cloud.githubusercontent.com/assets/687163/6940198/ab906a30-d874-11e4-8dd6-def7586bdda8.png)

Doesn't work for me in either 1.7 or 2.0.

**Comment by marcodaniel** [comment] 2015-04-01 12:27
Did you use the Beamer option "fragile"? It's always the best to insert a
completed minimal working example.

**Comment by heathermiller** [comment] 2015-04-01 13:14
Yes. + Here's your minimal example.

```latex
    \documentclass[t,aspectratio=169,xcolor={table}]{beamer}
    \setbeamersize{text margin right=2cm}
    \setbeamersize{text margin left=2cm}
    \usetheme{default}
    \usecolortheme{beaver}
    \usepackage{minted}

    \begin{document}
    \begin{frame}[fragile]\frametitle{Test slide}\label{test-slide}

    \begin{minted}[escapeinside=||]{py}
    def f(x):
    y = x|\colorbox{green}{**}|2
    return y
    \end{minted}


    \end{frame}
    \end{document}
```

Results in:

![screen shot 2015-04-01 at 3 13 28 pm](https://cloud.githubusercontent.com/assets/687163/6941634/ba3ee1e4-d881-11e4-8b20-f61ef13d6816.png)

**Comment by gpoore** [comment] 2015-04-01 14:51
@heathermiller Your example works for me. You will need minted 2.0 for this as well as Pygments 2.0+. My guess is that Pygments is the issue. You can check Pygments version by running `pygmentize -V` on the command line.

**Comment by heathermiller** [comment] 2015-04-01 15:33
Thanks for your response. Though still no dice. I'm using minted 2.0 ([2015/01/31 v2.0 Yet another Pygments shim for LaTeX]) and Pygments 2.02

    pygmentize -V
    Pygments version 2.0.2, (c) 2006-2014 by Georg Brandl.

I still get the same output as above.

**Comment by gpoore** [comment] 2015-04-01 16:27
@heathermiller I just upgraded from Pygments 2.0.1 to 2.0.2, and that still works for me, so the problem must be something else. Here are a few things you might try.

* Delete the *.aux file and the `_minted-<filename>` cache directory. Then recompile, making sure to reload the PDF.
* Check the log file. If there are compile errors, it's possible that there's an old copy of minted 1.7 somewhere that is causing problems. If there are compile errors, please post those here.
* Check for multiple Pygments installations. To get a list, `where pygmentize` under Windows, `which pygmentize` under most other systems. If you have multiple installations, there may be some reason that the wrong one is being used.

**Comment by marvin2k** [comment] 2015-06-12 14:54
Same here...

**Comment by gpoore** [comment] 2015-06-12 15:08
@marvin2k Is there any chance you have an old copy of `minted.sty` around somewhere? I've never been able to reproduce this issue, so some sort of problem with an old version of `minted` or Pygments is the only thing I can think of.

**Comment by marvin2k** [comment] 2015-06-12 15:28
Hm, indeed I had version 1.7 existing in `/usr/share/texlive/texmf-dist/tex/latex/minted/minted.sty`, and the recent version 2.0 in my local folder. But removing the old version does not change anything. `escapeinside=||` is accepted as option, but has no effect.

**Comment by gpoore** [comment] 2015-06-12 15:37
Can you try a different escape character, maybe `escapeinside=@@` or even something like `escapeinside=XX`? There might be some sort of issue with the way that the pipe character is being treated under some systems.

**Comment by marvin2k** [comment] 2015-06-12 15:41
Did `?`, `X` and `@` -- nothing. Putting two of 'em, like `XX`, will cause them not to be printed. The content in between is still not escaped to Latex.

**Comment by gpoore** [comment] 2015-06-12 15:59
Try inserting the following code somewhere in the document. It will insert the Pygments version that LaTeX is finding. If it is giving Pygments 2.0+, then there must be some sort system-dependent bug in `minted` that I will have to track down.

```latex
\makeatletter
\tt
\@@input|"pygmentize -V"
\makeatother
```

**Comment by marvin2k** [comment] 2015-06-12 21:05
Well, surprisingly this will print `Pygments version 2.0.1, (c) 2006-2014 by Georg Brandl.`

Funnily enough, the language seems to matter: using `py`, the OPs example and mine will work on two different Debian Jessie systems. But when using `bash` it will fail -- at least on these...

**Comment by gpoore** [comment] 2015-06-12 21:16
@marvin2k Can you give me the code for the `bash` case that fails? It's possible that there's a bug or incompatibility with some Pygments lexers.

**Comment by gpoore** [comment] 2015-06-13 17:03
The issue with `bash` is starting to clarify some things (though still not the original issue with the Python example from the docs).

Bash that doesn't work:
```latex
\begin{minted}[escapeinside=||]{bash}
declare -A a
|\colorbox{green}{i}|=1; j=2
a[$i,$j]=5
echo ${a[$i,$j]}
\end{minted}
```

Bash that does work (by redefining `!` to make colorboxes):
```latex
\begingroup
\catcode`\!=\active
\def!#1!{\colorbox{green}{#1}}
\begin{minted}[escapeinside=||]{bash}
declare -A a
|!i!|=1; j=2
a[$i,$j]=5
echo ${a[$i,$j]}
\end{minted}
\endgroup
```

Pygments' `escapeinside` works by [tokenizing to obtain strings and comments, then merging all non-string and non-comments tokens, then scanning these merged tokens for escapes, and finally scanning everything that wasn't escaped for normal tokens](https://bitbucket.org/birkenfeld/pygments-main/pull-request/230/update-the-patch-from-493-to-work-with-tip/diff). So it isn't possible to have escapes inside of strings and comments. That seems fine. However, the backslash `\` in `bash` is treated as a [`String.Escape` token](http://pygments.org/docs/tokens/) in the [`bash` lexer](https://bitbucket.org/birkenfeld/pygments-main/src/652e08e410f4f4f3a61add91f75ce5ed9d134711/pygments/lexers/shell.py?at=default). Because of this, standard LaTeX commands of the form `\command` will always be treated as starting with a type of string, which will then cause the `escapeinside` to fail, since it cannot include a string.

So ultimately this is running into limitations of Pygments, either in terms of the tokens being used, or in terms of the three-step tokenization approach. My guess is that the best solution would probably be to reimplement `escapeinside` to work in a single tokenization pass. But there may be reasons for not doing that...I'm not familiar with the Pygments internals. In the meantime, `escapeinside` is unfortunately very limited with some languages, although as the second example above shows, it is possible to work around this in at least some cases.

**Comment by marvin2k** [comment] 2015-06-15 15:52
Hm. Very nice, thanks for looking into that. My snippet which failed was `\tikz\coordinate(bla);` -- inserting coordinates into the text for later usage. Boxes and arrows and such.

Your workaround did indeed help me. This is more-or-less my current solution::

    \begin{frame}[fragile]
        \newcommand{\annotateBox}[2]{
            \begin{tikzpicture}[remember picture,overlay]%
                \only<#1>{\draw[color=red] (#2_low) rectangle (#2_up);}%
            \end{tikzpicture}%
        }

        \begingroup
        \tikzstyle{lower} = [baseline=.5ex]
        \tikzstyle{upper} = [baseline=-1.5ex]
        \catcode`\!=\active
        \def![#1]#2!{\tikz[lower]\coordinate(#1_low);#2\tikz[upper]\coordinate(#1_up);}
        \begin{minted}[escapeinside=||]{bash}
            packet: |![label]text!| blalbjsdlfjkh
        \end{minted}
        \endgroup

        \annotateBox{2-}{label}
    \end{frame}

which does the job....

**Comment by gpoore** [comment] 2015-06-23 23:16
I've opened an [issue at Pygments](https://bitbucket.org/birkenfeld/pygments-main/issue/1118/escapeinside-is-fragile-with-some-lexers) for the `escapeinside` issues with `bash`. I've added info about when `escapeinside` can fail, and the workaround, to the documentation for the next `minted` release.

I have never been able to reproduce the original issue of `escapeinside` not working with Python and beamer, so I am closing the issue. Please open a new issue for new or continuing issues with `escapeinside`.

**Closed by gpoore** 2015-06-23 23:16 UTC

**Comment by madgen** [comment] 2017-11-30 13:20
Similarly, it doesn't work for the prolog lexer (but works fine with python). Should we open another issue in Pygments repo?

**Comment by gpoore** [comment] 2017-11-30 17:10
@madgen If you can track down exactly why the prolog lexer fails, it might be worth opening another issue or commenting on the existing issue. However, due to the nature of the previous `escapeinside` issues, I'm still inclined to think that a reimplementation of `escapeinside`, rather than lexer modifications, is the best long-term solution.

**Comment by jswalens** [comment] 2018-01-22 14:05
I encounter the same issue in Clojure, where `\a` represents the character `a`. (Similarly, `\newline` is a newline, so `\` can be followed by one or more letters.) [The Pygments Clojure lexer parses this as a String.Char](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/jvm.py?at=default&fileviewer=file-view-default#jvm.py-823), which cannot be used in escapeinside.

I don't see a way to modify the lexer to work around this (`\newline` simply _is_ a String.Char), leading me to believe escapeinside should be implemented differently. (Instead of first lexing and then searching for escaped fragments, it'd make more sense to do it the other way around.)

**Comment by cykerway** [comment] 2020-06-23 19:22
The `bash` example is hopeless, because the lexer knows nothing about `escapeinside` chars. Note that this option is only read in the latex formatter, not the bash lexer. If the bash lexer knows about `escapeinside` chars, it would make an `Escape` token out of `|\colorbox{green}{i}|`, then the problem gets easier.

An escape split by a string `{ESC_LEFT...}{STR_LEFT...STR_RIGHT}{...ESC_RIGHT}` is almost always wrong. A string split by an escape `{STR_LEFT...}{ESC_LEFT...ESC_RIGHT}{...STR_RIGHT}` may work fine with a patch. In the latter case, the lexer needs to correctly get the string, and the formatter needs some additional processing.

I think the correct way to parse escapes is to make the lexer aware of escape chars. When the lexer finds an escape, it knows whether it is encapsulated in another token or not. If no, then easy, just spit an `Escape` token to the token stream. If yes, then the lexer probably should just leave the escape in the envelope (which is likely a string) and leave the job to the formatter.

**Comment by cykerway** [comment] 2020-06-23 19:58
OK, I made a patch for pygments, possibly related to this issue: https://github.com/pygments/pygments/issues/1485 It doesn't fix the lexer, but could make `escapeinside` more useful.

**Comment by gpoore** [comment] 2020-06-23 20:06
@cykerway Thanks for trying to improve Pygments! `escapeinside` has been very useful, but due to its limitations it has also been an almost constant source of issues.

**Comment by cykerway** [comment] 2020-06-23 20:25
@gpoore I tend to use such embedded macros as few as possible, but sometimes they are unavoidable, for example, if you want different font styles in the same verbatim environment. This patch assures backwards compatibility by adding another option `escapeinstr` which defaults to `False`, so this patch shouldn't change anything if user doesn't enable this option. Plus, the provided usage scenarios are tested and obviously working as expected. By following these known paths, issues are kept at their minimum.

Btw the patch for `minted` has only one line:

```tex
\minted@def@optcl@switch{escapeinstr}{-P escapeinstr}
```

If you like it feel free to merge it in. But I guess it must be waited until the underlying change is merged in Pygments.

**Comment by feffi** [comment] 2021-08-23 08:37
Hi, this issue was closed despite open issues? Why was it closed?
