### ISSUE TITLE
Minted fails to process multiline C/C++ macros if texcomments is used

### ISSUE THREAD

**Issue by LDVSOFT** [gpoore/minted#66] opened 2015-02-16 08:57 UTC
I have tried to typeset multiline macro and it failed. The example is:

    \documentclass{article}
    \usepackage{minted}
    
    \newminted{cpp}
    
    \begin{document}
    
    \begin{cppcode}
    #define I \
    am multiline \
    define
    \end{cppcode}
    
    \end{document}

The error is:

    ! Missing \endcsname inserted.
    <to be read again> 
                       \par 
    l.8 \begin{cppcode}

Works fine when using `\begin{minted}{cpp}`, though!

There are no cached output in _minted... directory, only default.pygstyle. I am using 2.0 version. Nothing interesting in log file. I tested on xelatex engine, but, as I think, it should not matter.

**Comment by gpoore** [comment] 2015-02-16 15:57
I think you want `\newminted{cpp}{}`. The syntax is `\newminted{<language>}{<default options>}`.

**Comment by LDVSOFT** [comment] 2015-02-17 10:08
Oh, I am so sorry, I failed at getting example. While doing the needed one, I got the true bug: `texcomments` can't be used while typesetting multiline defines in C++.

    \documentclass[12pt,a4paper]{report}
    \usepackage{minted}
    
    \newminted{cpp}{texcomments}
    
    \begin{document}
     
    \begin{cppcode}
    #define DefineArray(name, type) \
    class name{ \
       type *date; \
    };
    \end{cppcode}
    
    \end{document}

Or is it intended behaviour?

**Comment by LDVSOFT** [comment] 2015-02-17 10:26
The problem is, as I see, is minted/pygmets thinking C/C++ macro is a comment.

**Comment by gpoore** [comment] 2015-02-17 18:26
This is due to the Pygments approach to lexing preprocessor directives. It doesn't matter whether you are using `\newminted` or just a simple `\begin{minted}[texcomments]{cpp}`; you get the same result. `texcomments` causes comments to be treated as LaTeX code, and it turns out that Pygments treats preprocessor directives as comments. If you look at the [list of Pygments tokens](http://pygments.org/docs/tokens/), preprocessor directives show up as `Comment.Preproc`. And in the [definitions for C and C++](https://bitbucket.org/birkenfeld/pygments-main/src/41771329a71bc4ab86b0d4412d5933d95b658dfd/pygments/lexers/c_cpp.py?at=default), you will see this being used. So with `texcomments`, the body of the directive is treated as **literal** LaTeX code, and of course it isn't valid LaTeX so it breaks things.

Fixing this would require Pygments to have a separate token type for preprocessor directives, or alternatively ignoring `Comment.Preproc` for `texcomments`. It would probably be worth opening an issue at the [Pygments site](https://bitbucket.org/birkenfeld/pygments-main).

Additional technical detail follows, for future reference. Without `texcomments`, we get the Pygments output
```latex
\begin{Verbatim}[commandchars=\\\{\}]
\PYGdefault{c+cp}{\PYGdefaultZsh{}define DefineArray(name, type) \PYGdefaultZbs{}}
\PYGdefault{c+cp}{class name\PYGdefaultZob{} \PYGdefaultZbs{}}
\PYGdefault{c+cp}{   type *date; \PYGdefaultZbs{}}
\PYGdefault{c+cp}{\PYGdefaultZcb{};}
\end{Verbatim}
```
With `texcomments`, we get
```latex
\begin{Verbatim}[commandchars=\\\{\},codes={\catcode`\$=3\catcode`\^=7\catcode`\_=8}]
\PYGdefault{c+cp}{\PYGdefaultZsh{}define DefineArray(name, type) \}
\PYGdefault{c+cp}{class name{ \}
\PYGdefault{c+cp}{   type *date; \}
\PYGdefault{c+cp}{};}
\end{Verbatim}
```
The trailing `\` is treated as literal LaTeX, so it ends up escaping the closing `}`, which breaks everything.

**Comment by LDVSOFT** [comment] 2015-02-17 22:30
@gpoore Thank you for information, I have created Pygments [issue](https://bitbucket.org/birkenfeld/pygments-main/issue/1086/wrong-processing-of-in-c-c-macros-if-is). Hopefully, this will get resolved soon. I think you can close this issue as it is not a bug in minted.

**Comment by gpoore** [comment] 2015-06-23 21:46
I am closing this since the issue is in Pygments. I have added a note in the documentation for the next release about these kinds of potential problems with `texcomments`.

**Closed** 2015-06-23 21:46 UTC
Labels: pygments, question

**Comment by arbitrary-cat** [comment] 2016-01-11 16:03
My current workaround for this is to have my build-system create a copy of each file I'm including listings using the following sed program

```shell
mkdir -p $(dirname ${INP_FILE?})
sed -e 's/#define.*\\$/&textbackslash/' ${INP_FILE?} > listings-src/${INP_FILE?}
```

I then use that file as the source for the listings, not the actual source code, and it displays correctly without breaking LaTeX. For example

```latex
\inputminted[firstline=5,lastline=10,label=foo/bar.h]{c++}{listings-src/foo/bar.h}
```

**Comment by Hydronicx** [comment] 2016-01-11 17:22
Converting tabs to spaces in my input C files fixed this issue for me... It was also not displaying multi-line comments.
