### ISSUE TITLE
[Feature request] named code segments

### ISSUE THREAD

**Issue by AntonC9018** [gpoore/minted#394] opened 2024-05-11 14:02 UTC
It could be useful to have named segments in a source file, and be able to import segments by name from latex, to remove the dependency on code not moving around when specifying concrete line numbers.

Imagine a source file like this:
```
...
// Test segment begin
...
// Test segment end
...
```

```
\inputminted[segmentbegin=// Test segment begin, segmentend=// Test segment end]{lang}{file.lang}
```

I'm doing it with a custom script right now in my stuff.

**Comment by gpoore** [comment] 2024-05-25 17:06
Duplicate of #373.

This is now possible in v3.0.0beta1. If you would like to experiment with the beta version, installation instructions are [here](https://github.com/gpoore/minted/tree/v3-dev) and the [CHANGELOG](https://github.com/gpoore/minted/blob/v3-dev/latex/CHANGELOG.md) includes details about new features (the PDF documentation won't be fully updated until the final v3 release). Otherwise, the final v3 release should be available sometime in June.

**Closed by gpoore** 2024-05-25 17:06 UTC
