### ISSUE TITLE
defining "escapeinside" changes xml formatting, even if not used

### ISSUE THREAD

**Issue by hidders** [gpoore/minted#139] opened 2016-11-06 22:58 UTC
If "escapeinside" is defined certain attribute names no longer are recognised. A small example with escape inside:

```
 \documentclass{article}
 \usepackage{minted}
 \begin{document}
 \begin{minted}[escapeinside=||]{xml}
 <xsd:element name="item" maxOccurs="unbounded" />
 \end{minted}
 \end{document}
```

and without:

```
 \documentclass{article}
 \usepackage{minted}
 \begin{document}
 \begin{minted}[]{xml}
 <xsd:element name="item" maxOccurs="unbounded" />
 \end{minted}
 \end{document}
```

I would expect the same output, but in the first case the attribute maxOccurs remains black, but it is recognised in the second case. The general pattern seems to be that only the first attribute is recognised as such.

**Comment by gpoore** [comment] 2016-11-07 00:17
This looks like a duplicate of #103.  The way that Pygments does `escapeinside` [can be fragile](https://bitbucket.org/birkenfeld/pygments-main/issues/1118/escapeinside-is-fragile-with-some-lexers), and it looks like this is particularly true for xml. You might open an issue at the [Pygments site](https://bitbucket.org/birkenfeld/pygments-main/), although it seems that the pace of LaTeX-related improvements and bug fixes is quite slow.

**Comment by hidders** [comment] 2016-11-08 09:57
Ok. Thanks. I will take it to Pygments. It seems really a problem of the latex formatter, since in other formatters the output is fine. For example, if my input is:
`<element attribute1="string1" attribute2="string2" />`
And I run "pygmentize -f tex test.xml" on it, then I get:
```
\begin{Verbatim}[commandchars=\\\{\}]
\PY{n+nt}{\PYZlt{}element} 
  \PY{n+na}{attribute1=}\PY{l+s}{\PYZdq{}string1\PYZdq{}} 
  \PY{n+na}{attribute2=}\PY{l+s}{\PYZdq{}string2\PYZdq{}} 
\PY{n+nt}{/\PYZgt{}}
\end{Verbatim}
```
But if I run "pygmentize -f tex -O escapeinside=@@ test.xml", I get:
```
\begin{Verbatim}[commandchars=\\\{\},codes={\catcode`\$=3\catcode`\^=7\catcode`\_=8}]
\PY{n+nt}{\PYZlt{}element} 
  \PY{n+na}{attribute1=}\PY{l+s}{\PYZdq{}string1\PYZdq{}} 
  attribute2=\PY{l+s}{\PYZdq{}string2\PYZdq{}}
/\PYZgt{}
\end{Verbatim}
```

Anyway, I will file a bug report with the Pygmentizers. I might even start looking at the code of the formatter myself. I really need this to work because I use it a lot in my slides.

**Comment by gpoore** [comment] 2016-11-08 12:46
Yes, this is tied to the LaTeX formatter, but only because it is the only formatter that has `escapeinside`. I believe that Pygments is currently using a three-step tokenization process for `escapeinside`. If a single-step tokenization process could be developed, with `escapeinside` having highest priority, that might fix things. But I haven't tried to dig into the Pygments details to see if there would be downsides with that approach as well.

**Comment by hidders** [comment] 2016-11-11 13:09
Could it not be done without any tokenization? I mean, as far as I understand it, Pygments core task is about marking in an input text where certain classes begin and end. Assuming that it does not take out characters or add them, an escaped sequence can be taken out entirely, and after the marking you can always find that position back by simple counting. 

Let me illustrate. If your text is "abcdef gh|escaped stuff|ijk" then the position of the escaped stuff is position 10. Let's say after removing the escaped sequence and marking this becomes  "{abc}{def} {gh}{ijk}" then it would still be more or less clear where the escaped sequence belonged, namely after the 9th character, so between 'h' and 'i'. The ambiguity left would be if it belongs into the group {gh} or the group {ijk}, but that is a matter of agreeing on a convention like "it always goes in the group of the character right before it".

The advantage of this is that the core of Pygmentz and the person writing the syntax would not have to know about the escaped sequences, so a clear separation of concerns. It does however all rest upon the assumption that the mark-up part does not add or remove characters.

**Closed** 2017-07-09 00:29 UTC
Labels: pygments

**Comment by koppor** [comment] 2019-12-22 21:00
@hidders May I ask what your results of "taking it to pygments" were? They now have a GitHub repository with an issue tracker there: https://github.com/pygments/pygments/issues. I've been reminded of this during https://github.com/pygments/pygments/pull/1273.

**Comment by hidders** [comment] 2019-12-23 00:24
Hello Oliver,

I'm afraid I never got to that. At some point the lectures started so I just had to work with the slides that I had.

-- Jan

>
